### PR TITLE
A lot of improvements. 

### PR DESCRIPTION
**Pull request by Razzwan**
I know, that you will not agree with that, so, I created separate fork for developing it. Sorry, for that. If you wish, connect with me

### CODE REVIEW

**Comment by vkruglikov** [comment]
Hi @Razzwan 
What is the main idea of your improvements?

You added `isVersionAtLeast` as a hook, and Tma loader.

Can you use `isVersionAtLeast` directly from `useWebApp()` hook?

**Comment by Razzwan** [comment]
> Hi @Razzwan What is the main idea of your improvements?

Main idea is add TmaLoader

> You added `isVersionAtLeast` as a hook, and Tma loader.

> Can you use `isVersionAtLeast` directly from `useWebApp()` hook?

For sure. But it works incorrectly. Differently with numbers and with string version number. That's why I added this hook. 

There are two main reasons:

1. Find the project, where I can be not only one mainteiner
2. Add TmaLoader to simplify application start and be able support two version: Simple Web Application and Telegram Web Application

**Comment by Razzwan** [comment]
# I am suggesting 

1. Create an organization responsible for this package
2. Add joint ownership of this organization to more than one person 
3. Jointly support and develop this project for a long time

**Comment by vkruglikov** [comment]
Hi @Razzwan! Thank you for the activity!

I am closing this request for several reasons

- Some components and hooks are not related to the basic goals of the project. Of course, they can be convenient for any project, but you can always do this as a custom component in your project.
- No need to change basic project settings such as styling settings and branch names unless really necessary https://github.com/vkruglikov/react-telegram-web-app/pull/48/files#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34R6

Thank you very much for your desire to make the project better, please follow the instructions and first discuss all changes in the discussion section

https://github.com/vkruglikov/react-telegram-web-app/discussions/49#discussioncomment-7563305

**Pull request closed without merging**
